name: form_validator_flutter_example

publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  form_validator_flutter:
    path: ../

flutter:
  uses-material-design: true